version: '3'

services:
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 500M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - $PWD/scylla_config
    ports:
      - "9042:9042"
    networks:
      web:
        aliases:
          - scylla-node1

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 500M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - $PWD/scylla_config
    networks:
      web:
        aliases:
          - scylla-node2


  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 500M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - $PWD/scylla_config
    networks:
      web:
        aliases:
          - scylla-node3

networks:
  web:
    driver: bridge